Repository kakawutalk/kakawutalk, pull requests merged in 2021-10, with the labels that each got.

#4 [#3] feat : 아이디 찾기 template 추가
  src/main/java/com/example/chatproj/chatproj/controller/controller.java
  src/main/webapp/WEB-INF/jsp/find_id.jsp
Labels: feature

#6 [#5] refactor : template & controller refactor
  src/main/java/com/example/chatproj/chatproj/controller/controller.java
  src/main/resources/static/css/account_form.css
  src/main/resources/static/css/reset.css
  src/main/resources/static/css/signup.css
  src/main/resources/static/js/account_form.js
  src/main/webapp/WEB-INF/jsp/common/header.jsp
  src/main/webapp/WEB-INF/jsp/common/script.jsp
  src/main/webapp/WEB-INF/jsp/common/title.jsp
  src/main/webapp/WEB-INF/jsp/find_id.jsp
  src/main/webapp/WEB-INF/jsp/find_password.jsp
  src/main/webapp/WEB-INF/jsp/hello.jsp
  src/main/webapp/WEB-INF/jsp/signin.jsp
  src/main/webapp/WEB-INF/jsp/signup.jsp
  src/main/webapp/WEB-INF/jsp/test1.jsp
Labels: refactor

#14 [#13] feat : account signin
  src/main/java/com/example/chatproj/chatproj/controller/SigninForm.java
  src/main/java/com/example/chatproj/chatproj/controller/SignupForm.java
  src/main/java/com/example/chatproj/chatproj/controller/controller.java
  src/main/java/com/example/chatproj/chatproj/service/UserService.java
  src/main/webapp/WEB-INF/jsp/signin.jsp
  src/main/webapp/WEB-INF/web.xml
Labels: feature

#50 [#49] modify: chatpg 템플릿 수정
  src/main/resources/static/css/chatting_form.css
  src/main/webapp/WEB-INF/jsp/chatpg.jsp
Labels: modify
