Repository kakawutalk/kakawutalk, pull requests merged in 2022-01, with the labels that each got.

#129 Yunhes45/feat#128
  src/main/java/com/example/chatproj/chatproj/controller/controller.java
  src/main/java/com/example/chatproj/chatproj/repository/ChatRepository.java
  src/main/java/com/example/chatproj/chatproj/repository/JpaChatRepository.java
  src/main/java/com/example/chatproj/chatproj/repository/JpaUserRepository.java
  src/main/java/com/example/chatproj/chatproj/service/ChatService.java
  src/main/webapp/WEB-INF/jsp/2.jsp
  src/main/webapp/uploadfile/SjHbMCoEBdiFeOQzwfmfBptMNblKCREU.pptx
Labels: feature

#131 [#130] feat : 파일 업다운로드UI, 파일정보 뷰로 뿌려주기
  src/main/java/com/example/chatproj/chatproj/controller/controller.java
  src/main/java/com/example/chatproj/chatproj/domain/Fileupload_Table.java
  src/main/resources/static/css/chattingroom_form.css
  src/main/webapp/WEB-INF/jsp/2.jsp
  src/main/webapp/WEB-INF/jsp/chat.jsp
  src/main/webapp/uploadfile/uTxVUkfjKQRwMDMExRSLWUOIzXkLcveW.jpg
Labels: feature

#135 [#134] feat : 파일 다이얼로그 데이터 불러오기
  src/main/java/com/example/chatproj/chatproj/controller/FileuploadForm2.java
  src/main/java/com/example/chatproj/chatproj/controller/controller.java
  src/main/resources/static/css/chattingroom_form.css
  src/main/webapp/WEB-INF/jsp/chat.jsp
  src/main/webapp/uploadfile/fgUQHieWNrKHuiusKsXXFqDQnABNZKAE.png
Labels: feature

#140 [#136] modify : 날짜형식 버그
  src/main/java/com/example/chatproj/chatproj/controller/controller.java
  src/main/webapp/uploadfile/OJzSNIIJAoNizQGTDAACtXhvNxkbdEqu.png
  src/main/webapp/uploadfile/WVlfEKUtSgrZmpywSazRcyEnDYajAsZG.jpg
  src/main/webapp/uploadfile/jrcAaUZXPrTXpsMxxxfhyGducjJSskPI.jpg
  src/main/webapp/uploadfile/scEamGkGXezlbxYNcSoHtdJlskZPbowh.jpg
Labels: modify

#153 Yunhes45/bug#152
  src/main/java/com/example/chatproj/chatproj/controller/FileuploadForm2.java
  src/main/java/com/example/chatproj/chatproj/controller/controller.java
  src/main/java/com/example/chatproj/chatproj/repository/ChatRepository.java
  src/main/java/com/example/chatproj/chatproj/repository/JpaChatRepository.java
  src/main/java/com/example/chatproj/chatproj/service/ChatService.java
  src/main/resources/static/css/chattingroom_form.css
  src/main/webapp/WEB-INF/jsp/chat.jsp
  src/main/webapp/uploadfile/MweLVhSDempKtjuPFsigPCoxipBcUFwu.jpg
  src/main/webapp/userimg/39IcsefiMuEg1yYDq91MjdLnIr9OdGq7.png
  src/main/webapp/userimg/YUpyAyZge4BaPmuxKMcnjxcxTkRWnrXl.jpg
Labels: bug

#154 [#152] bug : #142 #149 충돌 이슈(수정)
  src/main/resources/static/css/chattingroom_form.css
  src/main/webapp/WEB-INF/jsp/chat.jsp
Labels: bug

#155 [#151] modify: 파일 리스트 css 수정
  src/main/resources/static/css/chattingroom_form.css
  src/main/webapp/WEB-INF/jsp/chat.jsp
  src/main/webapp/uploadfile/mplcWIwXTClFynFRymYTlerdakhVZbFi.jpg
  src/main/webapp/uploadfile/qISmiuIGZGgKVFCTzOLVuPpukPSXgbVU.jpg
  src/main/webapp/uploadfile/xBQRFiPShbSOVdbfsAJaYjtdcmefSFTz.jpg
  src/main/webapp/userimg/iZn1ppIhVFHO2DsvVbsKZCEhFlxpOJFs.jpg
  src/main/webapp/userimg/menu_icon.png
Labels: modify

#156 [#147] feat : 회원 탈퇴
  src/main/java/com/example/chatproj/chatproj/controller/controller.java
  src/main/java/com/example/chatproj/chatproj/repository/JpaUserRepository.java
  src/main/java/com/example/chatproj/chatproj/repository/UserRepository.java
  src/main/java/com/example/chatproj/chatproj/service/UserService.java
  src/main/webapp/WEB-INF/jsp/common/header.jsp
  src/main/webapp/uploadfile/MweLVhSDempKtjuPFsigPCoxipBcUFwu.jpg
  src/main/webapp/uploadfile/mplcWIwXTClFynFRymYTlerdakhVZbFi.jpg
  src/main/webapp/uploadfile/qISmiuIGZGgKVFCTzOLVuPpukPSXgbVU.jpg
  src/main/webapp/uploadfile/xBQRFiPShbSOVdbfsAJaYjtdcmefSFTz.jpg
  src/main/webapp/userimg/39IcsefiMuEg1yYDq91MjdLnIr9OdGq7.png
  src/main/webapp/userimg/KS3qs33sacRIh5GhHv0fMVHRzkNKunpA.png
  src/main/webapp/userimg/TNDmb93gxZAWV6sF0BZ1YSvRUaHP7e68.png
  src/main/webapp/userimg/YUpyAyZge4BaPmuxKMcnjxcxTkRWnrXl.jpg
  src/main/webapp/userimg/iZn1ppIhVFHO2DsvVbsKZCEhFlxpOJFs.jpg
  src/main/webapp/userimg/t2aFWiaFg6qIh6rPMWsi5OPzPdjTPabZ.jpg
Labels: feature

#159 [#148] feat : 회원정보수정
  src/main/java/com/example/chatproj/chatproj/controller/controller.java
  src/main/java/com/example/chatproj/chatproj/repository/JpaUserRepository.java
  src/main/java/com/example/chatproj/chatproj/repository/UserRepository.java
  src/main/java/com/example/chatproj/chatproj/service/UserService.java
  src/main/webapp/WEB-INF/jsp/common/header.jsp
  src/main/webapp/WEB-INF/jsp/modifyUser.jsp
  src/main/webapp/userimg/JcQEUwCw2C5o057kKdyAxMR2WzlhT46d.png
  src/main/webapp/userimg/UO3cNJTOOvzDlP3ijEyxZmT8ymghHyqA.jpg
  src/main/webapp/userimg/UTTAaMvZ3WZwbrYyLh9XXxp8eGGfyEBX.png
Labels: feature

#161 [#158] modify: 프로필 이미지 등록 시 미리보기 기능
  src/main/webapp/WEB-INF/jsp/signup.jsp
  src/main/webapp/uploadfile/sCFKPUfefwxlwZjeTPaSwvajbUDDQKDO.jpg
  src/main/webapp/userimg/8i2PdGZ8hLas9tFIByrVgBpIB5Dk5fqy.jpg
Labels: modify

#167 [#166] feat : 채팅방 참여자 목록
  src/main/java/com/example/chatproj/chatproj/controller/controller.java
  src/main/java/com/example/chatproj/chatproj/repository/JpaUserRepository.java
  src/main/java/com/example/chatproj/chatproj/repository/UserRepository.java
  src/main/java/com/example/chatproj/chatproj/service/UserService.java
  src/main/resources/static/css/chattingroom_form.css
  src/main/webapp/WEB-INF/jsp/chat.jsp
Labels: feature

#169 [#168] modify: 채팅방 Modal 디자인 수정
  src/main/resources/static/css/chattingroom_form.css
  src/main/webapp/WEB-INF/jsp/chat.jsp
  src/main/webapp/userimg/EqSJ56QPCaRILJhazWdrRUJ507F8q3cL.jpg
  src/main/webapp/userimg/MJqJqPQq3qN8lf43B6MzFZ1KBsUZMFNx.jpg
  src/main/webapp/userimg/vYlwuhhPLaXvg9bGUD1ZsPi7tHrbwBs7.jpg
  src/main/webapp/userimg/yMG7Ek24ZwPH4NmVG2yzCUNRTGWQIr2T
Labels: modify

#171 [#170] modify : 파일 소켓 전송 완료
  src/main/java/com/example/chatproj/chatproj/controller/controller.java
  src/main/java/com/example/chatproj/chatproj/domain/Chatlog_Table.java
  src/main/java/com/example/chatproj/chatproj/repository/ChatRepository.java
  src/main/java/com/example/chatproj/chatproj/repository/JpaChatRepository.java
  src/main/java/com/example/chatproj/chatproj/service/ChatService.java
  src/main/webapp/WEB-INF/jsp/chat.jsp
  src/main/webapp/uploadfile/CXhzsbQyaHsQqfzbjgtWXWricyzWEdHD.jpg
  src/main/webapp/uploadfile/EmfjiwVvuuBElQLyMslanxPfEfzMsagL.jpg
  src/main/webapp/uploadfile/KIpOTtVTyAevRqMRuAffrfSqvTKGnQYU.jpg
  src/main/webapp/uploadfile/KvEWGeXzisOvqiAlmSUhXhgnGPcBKSxq.jpg
  src/main/webapp/uploadfile/LdIbfUkipXUDZIsawxnnqWUSwfQzHlXU.png
  src/main/webapp/uploadfile/MDgqSJSlgocvpcRwOWSSrgXVCpBQnPtC.jpg
  src/main/webapp/uploadfile/fSudSXjjkHFGADJzhaLdxFDjTIFOIuji.jpg
  src/main/webapp/uploadfile/kKxZCLJdNUcuaNNRVrZVruKwjTYkjFmy.pptx
  src/main/webapp/uploadfile/sCFKPUfefwxlwZjeTPaSwvajbUDDQKDO.jpg
  src/main/webapp/uploadfile/uZZsFAPsomKIyWIAtiKAkeblGfvkpOQF.jpg
  src/main/webapp/uploadfile/vRHOqehAzJIRxLKCRzVjQPuHrgvclkeS.png
  src/main/webapp/uploadfile/xeQIUnkFRfYjhGQibfNrzFTVIbXEJUef.jpg
Labels: modify

#173 [#172] modify : 파일 전송UI 수정
  src/main/java/com/example/chatproj/chatproj/controller/FileuploadForm2.java
  src/main/java/com/example/chatproj/chatproj/controller/controller.java
  src/main/java/com/example/chatproj/chatproj/domain/Chatlog_Table.java
  src/main/resources/static/css/chattingroom_form.css
  src/main/webapp/WEB-INF/jsp/chat.jsp
  src/main/webapp/uploadfile/MpjHJwwCclTwBJOAaQSZLaSEBCDbSRpr.jpg
  src/main/webapp/uploadfile/NIdSveBSurtXWVCXAEvLlFqOlgxCGeaC.jpg
  src/main/webapp/uploadfile/PnNTrkhzShBPHwmbVsmihNmtfcJRBiwF.jpg
  src/main/webapp/uploadfile/iSDHmiyZMwkQDhMAgPHoUoEvpdiUaplG.jpg
  src/main/webapp/uploadfile/iXGeYtmDfwduvKBPhNHRJbUSFzLkxhYx.jpg
  src/main/webapp/uploadfile/jikMMtLOltDReYQyymGXMVnQrfnQBHPV.jpg
  src/main/webapp/uploadfile/mMQuBTnRJpoWylEttJBWivUwusVJckIX.pptx
  src/main/webapp/uploadfile/nBXFhAfYbOzSArClXRtTbcvJASXAqVwq.jpg
  src/main/webapp/uploadfile/ocZbilbUPEvTGUsgbphjCAXpDDcOruGj.png
  src/main/webapp/uploadfile/vZSYLwXFFrdiisjsnNKopdwHzURyXeFx.png
Labels: modify

#175 [#174] refactor : chat 페이지 리팩토링
  src/main/resources/static/js/AjaxController.js
  src/main/resources/static/js/socket.js
  src/main/webapp/WEB-INF/jsp/chat.jsp
  src/main/webapp/WEB-INF/jsp/modifyUser.jsp
  src/main/webapp/userimg/D9ysY11qwOsnrzVFaNKniIl1DiQ6DKS0.jpg
  src/main/webapp/userimg/MBPQxZL3mf4StG5gsg8DYythXg4LQuoi.png
Labels: refactor

#179 [#178] refactor : 중복 쿼리 통합
  src/main/java/com/example/chatproj/chatproj/controller/controller.java
  src/main/java/com/example/chatproj/chatproj/repository/ChatRepository.java
  src/main/java/com/example/chatproj/chatproj/repository/JpaChatRepository.java
  src/main/java/com/example/chatproj/chatproj/repository/JpaUserRepository.java
  src/main/java/com/example/chatproj/chatproj/repository/UserRepository.java
  src/main/java/com/example/chatproj/chatproj/service/ChatService.java
  src/main/java/com/example/chatproj/chatproj/service/UserService.java
  src/main/webapp/uploadfile/bENewxYUBDUKaDSGtMsqKndUxOqyouNU.jpg
Labels: refactor

#182 [#180] test : 배포테스트 3.0
  src/main/resources/application.properties
Labels: test

#185 [#183] bug : 채팅방 방제목 길이 제한
  src/main/resources/application.properties
  src/main/webapp/WEB-INF/jsp/InviteUser.jsp
Labels: bug

#187 [#186] modify : 파일리스트 페이징처리
  src/main/java/com/example/chatproj/chatproj/controller/controller.java
  src/main/java/com/example/chatproj/chatproj/repository/ChatRepository.java
  src/main/java/com/example/chatproj/chatproj/repository/JpaChatRepository.java
  src/main/java/com/example/chatproj/chatproj/service/ChatService.java
  src/main/webapp/WEB-INF/jsp/chat.jsp
  src/main/webapp/uploadfile/AaKEcBgsOSjqswYtcudNLUvaHtLTHeKX.jpg
  src/main/webapp/uploadfile/CQCMFMwmWnnmBfDShnxZgUdscilwjLEp.jpg
  src/main/webapp/uploadfile/IwsBbspvhERAHvHRqmNzsAnfJLrwLXnA.jpg
  src/main/webapp/uploadfile/KUKvsKnPzdjhnFDovvpydCwLgNyzLkll.jpg
  src/main/webapp/uploadfile/NniXVUPNboHUjBfRQaOgFJYOnFAvQebV.png
  src/main/webapp/uploadfile/QlWWJvTDWWnVPDILTXSeOyrPcIDdvABa.jpg
  src/main/webapp/uploadfile/ThfIEVgQqMMOhWiwlVHPxLbMywcutKOK.jpg
  src/main/webapp/uploadfile/UBNclUmjwkNjgEAhvGglfJfPHezSdCkJ.jpg
  src/main/webapp/uploadfile/UxvJixUaZsEXYcVxkpdRvyQtsIocaocA.jpg
  src/main/webapp/uploadfile/fLUbtvWIjXCqvZCnNxZptYHZnVGTNuYT.jpg
  src/main/webapp/uploadfile/pugbdnxRUJYxQTRKivXOhJzThqrdSNGx.jpg
  src/main/webapp/uploadfile/uLyEcTKHRRkWnSsMPDtQSfkWUAGrFzAf.jpg
  src/main/webapp/uploadfile/wjDRcIRoorBDfZCXjTSlefWWQIJXJOfH.jpg
  src/main/webapp/uploadfile/xHLOAlUlVBbNPWiYXWyKDfnNchhsITxw.png
  src/main/webapp/uploadfile/xToYInSGqqpKrAaEgWfgPMDPTLjUXblq.jpg
  src/main/webapp/uploadfile/xYGqZFzVnSAloitJcrPBxWJAnFfAMtqW.jpg
Labels: modify

#191 [#190] modify : 파일리스트 모달 창 닫기버튼 및 페이징 처리 이식
  src/main/webapp/WEB-INF/jsp/chat.jsp
Labels: modify

#193 [#192] bug : 파일리스트 모달창 첫번 째 파일 다운로드 안받아지는 버그
  src/main/webapp/WEB-INF/jsp/chat.jsp
Labels: bug

#196 [#194] dist : docker connect
  Distribute/distribute
  Distribute/dockerconnect
  table.sql
Labels: distribute

#200 [#199] modify : 파일리스트 없는 페이지 파라미터 입력 시 처리
  src/main/java/com/example/chatproj/chatproj/controller/controller.java
  src/main/webapp/WEB-INF/jsp/chat.jsp
Labels: modify

#201 [#199] modify : 파일리스트 없는 페이지 파라미터 입력 시 처리
  src/main/java/com/example/chatproj/chatproj/controller/controller.java
Labels: modify

#203 [#202] bug : 파일 삭제 후 삭제된 파일 다운로드 진행 시 예외 버그
  src/main/java/com/example/chatproj/chatproj/controller/controller.java
  src/main/webapp/WEB-INF/jsp/chat.jsp
  src/main/webapp/uploadfile/KUKvsKnPzdjhnFDovvpydCwLgNyzLkll.jpg
  src/main/webapp/uploadfile/UBNclUmjwkNjgEAhvGglfJfPHezSdCkJ.jpg
Labels: bug
